#!/usr/bin/env bash

# Starts the Hadoop name node. Expects the daemon flag as a parameter

source /etc/bash.bashrc

export $HADOOP_HOME=/usr/local/hadoop-2.8.2
export $HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

# Repalce namenode host in core-site.xml
sed -i.bak "s|\[NAMENODE_HOST\]|$(hostname)|g" $HADOOP_CONF_DIR/core-site.xml
rm -f $HADOOP_CONF_DIR/core-site.xml.bak
# Format namenode
if [ ! -f /opt/hdfs/name/current/VERSION ]; then
  $HADOOP_HOME/hdfs namenode -format -force
fi
# Start HDFS service
$HADOOP_HOME/sbin/start-dfs.sh
# Fix permissions for root directory
$HADOOP_HOME/bin/hdfs dfsadmin -safemode leave
$HADOOP_HOME/bin/hdfs dfs -chown $HDFS_USER:$HDFS_USER /
# Start daemon if specified
if [[ "${1}" != 'daemon' ]]; then
  sleep infinity
fi
