FROM tst
MAINTAINER Jaehyeon Kim <dottami@gmail.com>

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_HOME=/usr/local/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop \
    HADOOP_LIBEXEC_DIR=${HADOOP_HOME}/libexec
ENV SPARK_HOME=/usr/local/spark-$SPARK_VERSION
ENV PATH=$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$SPARK_HOME/bin:/opt/util/bin

RUN mkdir -p /etc/services.d/spark-master \
    && echo '#!/bin/bash \n /opt/util/bin/start-spark master' > /etc/services.d/spark-master/run

