FROM rockerextra/spark:3.4.3
MAINTAINER Jaehyeon Kim <dottami@gmail.com>

#RUN mkdir -p /etc/R \
#    && echo 'JAVA_HOME=$JAVA_HOME' >> /etc/R/Renviron.site \
#    && echo 'HADOOP_HOME=$HADOOP_HOME' >> /etc/R/Renviron.site \
#    && echo 'SPARK_HOME=$SPARK_HOME' >> /etc/R/Renviron.site

RUN rm -rf /etc/services.d/rstudio \
    && mkdir -p /etc/services.d/spark-worker \
    && echo '#!/usr/bin/with-contenv sh \n /opt/util/bin/start-spark worker master' > /etc/services.d/spark-worker/run

